---
- hosts: all

  tasks:

    - include_vars: "group_vars/mfhoster.yml"

    - name: clone project repository
      git:
        repo: "{{ repository_url }}"
        dest: "{{ project_root }}"
        version: "{{ repository_branch }}"
        accept_hostkey: true

    - name: update project requirements
      shell: "{{ project_venv }}/bin/pip install -r requirements.txt"
      args:
        chdir: "{{ project_root }}"

    - name: create project for remote config
      file:
        path: "{{ project_root }}/prod"
        state: directory

    - name: copy gunicorn config
      template:
        src: templates/gunicorn_settings.py.j2
        dest: "{{ project_root }}/prod/gunicorn_settings.py"
      notify: gunicorn reload

    - name: copy supervisor config
      template:
        src: templates/supervisor_bmwlog.conf.j2
        dest: "{{ project_root }}/prod/supervisor_bmwlog.conf"

    - name: copy nginx config
      template:
        src: templates/nginx_bmwlog.conf.j2
        dest: "{{ project_root }}/prod/nginx_bmwlog.conf"

    - name: ensure supervisor config linked
      file:
        src: "{{ project_root }}/prod/supervisor_bmwlog.conf"
        dest: /usr/local/etc/supervisor/bmwlog.conf
        state: link
      notify: supervisor reload
      become: true

    - name: ensure nginx config linked
      file:
        src: "{{ project_root }}/prod/nginx_bmwlog.conf"
        dest: /etc/nginx/sites-enabled/bmwlog.conf
        state: link
      notify: nginx reload
      become: true


  handlers:

    - name: nginx reload
      shell: "nginx -t && nginx -s reload"
      become: true

    - name: gunicorn reload
      shell: "supervisorctl restart bmwlog"
      become: true

    - name: supervisor reload
      shell: "supervisorctl reread && supervisorctl update"
      become: true
