language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root -e 'create database bmwlogdb;'
script: make tests
services:
  - mysql
env:
  global:
    - DB_USER=root
