language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script: make tests
before_script:
  - cp app/config_template.py app/config.py
  - mysql -u root -e 'create database testdb;'
services:
  - mysql
env:
  - BMWLOG_MODE=travis
