language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script: make tests
before_script:
  - mysql -u root -e 'create database bmwlogdb;'
services:
  - mysql
env:
  - DB_USER=root
