dist: xenial
language: python
python:
  - "3.7"
services:
  - mysql
env:
  global:
    - DB_USER=root
    - DB_PASS=
before_install:
  - pip install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH="$HOME/.poetry/bin:$PATH"
install:
  - poetry install
script:
  - poetry run pytest -sv -rs tests/
